name: (Test + Build) → Release # Can’t use commas because we use this name in cache keys 🤷‍♂️

# We want to run the job `test` for every single push for every single branch, whether or not a PR
# is open. The job `build` OTOH takes too long to run it for every single push, so it has an `if`
# condition — see below.
on: [push, pull_request]

jobs:
  test:
    name: Run tests
    # Without this, every push to a branch with an open PR would trigger two executions of this job,
    # one of which would be redundant.
    if: |
      (github.event_name == 'push' && github.ref == 'ref/head/main')
      ||
      (github.event_name == 'pull_request' && (   github.event.action == 'opened'
                                               || github.event.action == 'synchronize'
                                               || github.event.action == 'reopened'))
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
        java: [8, 11]
        suite: [examples, properties]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env: { cache-version: v1 }
        with:
          path: |
            .cpcache
            ~/.m2
            ~/.gitlibs
          key: ${{ format('{0}-{1}-{2}-{3}', runner.os, github.workflow, env.cache-version, hashFiles('deps.edn')) }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jre
      - uses: DeLaGuardo/setup-clojure@2.0
        with: { tools-deps: '1.10.1.536' }
      - run: bin/kaocha ${{ matrix.suite }}

  build:
    name: Build executables
    # This job takes way too long (~5 mins as of this writing) to do it on every single push, even
    # when no PR is open. So we’ll run it for pushes to main (which includes merging a PR) and
    # when opening, synchronizing (pushing to), or reopening a PR.
    if: |
      (github.event_name == 'push' && github.ref == 'ref/head/main')
      ||
      (github.event_name == 'pull_request' && (   github.event.action == 'opened'
                                               || github.event.action == 'synchronize'
                                               || github.event.action == 'reopened'))
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java8'
      - run: gu install native-image
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'
      - uses: actions/checkout@v2
      - run: bin/build-native-image
      - name: Upload artifact
        if: success() && contains(matrix.os, 'ubuntu')
        uses: actions/upload-artifact@v2
        with:
          name: dad-linux-amd64
          path: target/dad
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: success() && contains(matrix.os, 'macos')
        with:
          name: dad-mac-amd64
          path: target/dad

  release:
    name: Create release
    needs: [test, build]
    # Without this, every push to a branch with an open PR would trigger two executions of this job,
    # one of which would be redundant.
    if: |
      (github.event_name == 'push' && github.ref == 'ref/head/main')
      ||
      (github.event_name == 'pull_request' && (   github.event.action == 'opened'
                                               || github.event.action == 'synchronize'
                                               || github.event.action == 'reopened'))
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Download artifacts from step “build”
         uses: actions/download-artifact@v2
       - name: Export env vars RELEASE_TAG and PRERELEASE
         env:
           GITHUB_BRANCH: ${{ github.head_ref || github.ref }}
         run: .github/workflows/bin/release-vars
       - name: Prepare artifacts for upload as assets
         run: |
           tar -czvf dad-linux-amd64-${RELEASE_TAG}.tar.gz dad-linux-amd64
           tar -czvf dad-mac-amd64-${RELEASE_TAG}.tar.gz dad-mac-amd64
       - name: Create release
         id: create_release
         uses: actions/create-release@v1.1.1 # Includes https://github.com/actions/create-release/pull/32
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions
         with:
           tag_name: ${{ env.RELEASE_TAG }}
           commitish: ${{ github.event.pull_request.head.sha || github.sha }}
           draft: false
           prerelease: ${{ env.PRERELEASE }}
       - name: Upload Linux release asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: dad-linux-amd64-${{ env.RELEASE_TAG }}.tar.gz
           asset_name: dad-linux-amd64-${{ env.RELEASE_TAG }}.tar.gz
           asset_content_type: application/x-tar
       - name: Upload Mac release asset
         uses: actions/upload-release-asset@v1
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by Actions
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: dad-mac-amd64-${{ env.RELEASE_TAG }}.tar.gz
           asset_name: dad-mac-amd64-${{ env.RELEASE_TAG }}.tar.gz
           asset_content_type: application/x-tar
