name: Test & Build

on:
  push:
    paths:
      - '.circleci/**'
      - 'bin/**'
      - 'deps.edn'
      - 'src/**'
      - 'test/**'
      - 'tests.edn'

  # Only runs when the pull_request event’s activity type is opened, synchronize, or reopened.
  # https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
  pull_request: {}
  
jobs:
  test:
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
        java: [11, 13, 14]
        suite: [examples] # We don’t have any other suites yet but we hope to, soon!
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        env: { cache-version: v1 }
        with:
          path: |
            .cpcache
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-${{ github.workflow }}-${{ env.cache-version }}-${{ hashFiles('deps.edn') }}
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
          java-package: jre
      - uses: DeLaGuardo/setup-clojure@2.0
        with: { tools-deps: '1.10.1.536' }
      - run: bin/kaocha ${{ matrix.suite }}

  build:
    name: Build executables
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-18.04]
    timeout-minutes: 30
    runs-on: ${{ matrix.os }}
    steps:
      - uses: DeLaGuardo/setup-graalvm@3
        with:
          graalvm-version: '20.1.0.java8'
      - run: gu install native-image
      - uses: DeLaGuardo/setup-clojure@2.0
        with:
          tools-deps: '1.10.1.536'
      - uses: actions/checkout@v2
      - run: bin/build-native-image
      - name: Upload artifact
        if: ${{ success() && contains(matrix.os, 'ubuntu') }}
        uses: actions/upload-artifact@v2
        with:
          name: dad-linux-amd64
          path: target/dad
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        if: ${{ success() && contains(matrix.os, 'macos') }}
        with:
          name: dad-mac-amd64
          path: target/dad
